### ISSUE TITLE
Error occurred when executing Unique3DRun - MVPrediction:  No module named 'accelerate'

### ISSUE THREAD

**Issue by GonDesign** [jtydhr88/ComfyUI-Unique3D#23]
Error occurred when executing Unique3DRun - MVPrediction:

No module named 'accelerate'

**Comment by WanderFox** [comment]
python.exe -m pip install accelerate   

Also don't forget to "(Windows) Download the trition whl from https://huggingface.co/madbuda/triton-windows-builds, because it uses python 311, so download whl build for py311 and place it under ComfyUI-Unique3D folder.
(Windows) run install_windows_portable_win_py311_cu121.bat inside ComfyUI-Unique3D
answer Y while asking remove something"
